// <auto-generated/>
using System.Reflection;

[assembly: AssemblyVersionAttribute("1.0.5")]
[assembly: AssemblyFileVersionAttribute("1.0.5")]
[assembly: AssemblyInformationalVersionAttribute("1.0.5 ea7c13")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.0.5";
    }
}
