// <auto-generated/>
using System.Reflection;

[assembly: AssemblyVersionAttribute("1.0.7")]
[assembly: AssemblyFileVersionAttribute("1.0.7")]
[assembly: AssemblyInformationalVersionAttribute("1.0.7 c21f9c")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyVersion = "1.0.7";
        internal const System.String AssemblyFileVersion = "1.0.7";
        internal const System.String AssemblyInformationalVersion = "1.0.7 c21f9c";
    }
}
