// <auto-generated/>
using System.Reflection;

[assembly: AssemblyProductAttribute("Meerkat.Caching")]
[assembly: AssemblyCopyrightAttribute("Copyright � 2016 Paul Hatcher")]
[assembly: AssemblyVersionAttribute("2.1.0")]
[assembly: AssemblyFileVersionAttribute("2.1.0")]
[assembly: AssemblyInformationalVersionAttribute("2.1.0 61e81f")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyProduct = "Meerkat.Caching";
        internal const System.String AssemblyCopyright = "Copyright � 2016 Paul Hatcher";
        internal const System.String AssemblyVersion = "2.1.0";
        internal const System.String AssemblyFileVersion = "2.1.0";
        internal const System.String AssemblyInformationalVersion = "2.1.0 61e81f";
    }
}
